### ISSUE TITLE
REI deprecated entrypoint 

### ISSUE THREAD

**Issue by Mattabase** [Tigereye504/chestcavity#69]
![image](https://user-images.githubusercontent.com/2126947/174157191-07acacea-5b58-4fb6-8357-210d0b48435d.png)

**Comment by jaredniegas** [comment]
Hope this gets fixed soon.

**Comment by Dragonfly-Totem** [comment]
When attempting to do so with Chest Cavity 2.16.3 and Roughly Enough Items 9.1.517, I get the error reported by Mattabase in singleplayer, but can continue past it and it seems to function fine.

However, attempting to load this into a server space seems to be a critical failure and causes a crash-to-desktop.  Looking through the errors spat out during server load, it definitely seems to be caused by this mod's incompatibility.

**Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by Chest Cavity. Please use "rei_server", "rei_client" or "rei_common" instead.**

**Comment by MarbleGateKeeper** [comment]
Get same issue today. Both newest version.

**Comment by OctoRocket** [comment]
I have also encountered this issue.
