### ISSUE TITLE
Buffs/debuffs stay after uninstalling this mod, 0 negative doesn't work

### ISSUE THREAD

**Issue by wemdne** [Tigereye504/chestcavity#84]
As the title says, I uninstalled this mod and dragged it out of the mod folder after I found out the problem where the 0 negative doesn't work on my weapon and armor, I emptied my chest before uninstall, but the debuffs of empty organs stayed after uninstalling this mod, I deleted the config file as well, but it didn't work, and I cannot clear it with milk. 1.19 fabric.

**Comment by DarianLStephens** [comment]
Were you trying to store a weapon and armor in your chest cavity? Because O Negative just stops organs from being rejected, which weapons and armor never would because they're artificial.
O Negative II is what lets new organs _stay_ in the chest cavity after death.

The other problem is probably related to the player's entity attributes being changed. I'm surprised you didn't run the command to reset your chest cavity before uninstalling.

**Comment by wemdne** [comment]
I'll go and try to store them in the chest. For the attributes, I didn't know I should reset it before uninstall. It's fixed when I reinstall it tho. Thanks for the help :)
